name: cpustat
summary: periodic cpu utilization statistics
description: cpustat periodically reports the current CPU utilization of running tasks and can optionally report per CPU and per task utilization statistics at the end of a run.  cpustat has been designed and optimized to use a minimal amount of CPU cycles to monitor a system hence it is a light weight alternative to traditional process monitoring tools such as top.
confinement: strict
assumes: [snapd2.45]
base: core18
adopt-info: cpustat

architectures:
    - build-on: s390x
    - build-on: ppc64el
    - build-on: arm64
    - build-on: armhf
    - build-on: amd64
    - build-on: i386

parts:
    cpustat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/cpustat
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"

        build-packages:
            - gcc
            - make
            - libncurses5-dev
apps:
    cpustat:
        command: usr/sbin/cpustat

